type User {
    username: String
    password: String
    list: [List]
}
type List {
    title: String
    score: Integer
    status: String
}
type Game {
    title: String
    summary: String
    img: String
    info: [Info]
    systemReq: [SystemReq]
}
type Info {
    developer: String
    publisher: String
    releaseDate: Date
    genres: String
    rating: String
}
type SystemReq {
    os: String
    processor: String
    memory: String
    graphics: String
    storage: String
}

type Query {
    
}

query getUserInfo { 
    User {
        username
        list {
            title
            score
            status
        }
    }
}
query getGameInfo {
    Game {
        title
        summary
        img
        info {
            developer
            publisher
            releaseDate
            genres
            rating
        }
        system_req {
            os
            processor
            memory
            graphics
            storage
        }
    }
}
